/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedDashboardUserClientRouteImport } from './routes/_protected/dashboard/user/client'
import { Route as ProtectedDashboardUserMeRouteImport } from './routes/_protected/dashboard/user/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardUserClientRoute =
  ProtectedDashboardUserClientRouteImport.update({
    id: '/user/client',
    path: '/user/client',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardUserMeRoute =
  ProtectedDashboardUserMeRouteImport.update({
    id: '/user/me',
    path: '/user/me',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/dashboard/user/client': typeof ProtectedDashboardUserClientRoute
  '/dashboard/user/me': typeof ProtectedDashboardUserMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/user/client': typeof ProtectedDashboardUserClientRoute
  '/dashboard/user/me': typeof ProtectedDashboardUserMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/user/client': typeof ProtectedDashboardUserClientRoute
  '/_protected/dashboard/user/me': typeof ProtectedDashboardUserMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/user/client'
    | '/dashboard/user/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/dashboard'
    | '/dashboard/user/client'
    | '/dashboard/user/me'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/unauthorized'
    | '/_protected/dashboard'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/user/client'
    | '/_protected/dashboard/user/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/user/client': {
      id: '/_protected/dashboard/user/client'
      path: '/user/client'
      fullPath: '/dashboard/user/client'
      preLoaderRoute: typeof ProtectedDashboardUserClientRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/user/me': {
      id: '/_protected/dashboard/user/me'
      path: '/user/me'
      fullPath: '/dashboard/user/me'
      preLoaderRoute: typeof ProtectedDashboardUserMeRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardUserClientRoute: typeof ProtectedDashboardUserClientRoute
  ProtectedDashboardUserMeRoute: typeof ProtectedDashboardUserMeRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardUserClientRoute: ProtectedDashboardUserClientRoute,
  ProtectedDashboardUserMeRoute: ProtectedDashboardUserMeRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
